AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.0

Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/ClassAndModuleChildren:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/TrivialAccessors:
  AllowPredicates: true

# Need discussion
Style/Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/ModuleFunction:
  Enabled: false

# Needs refactors
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/PredicateName:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
