language: ruby
rvm:
  - 2.4.1
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
matrix:
  # Rubinius periodically fails in general, and it always segfaults for RuboCop
  # in particular. Until we figure out how to make it work consistently, allow
  # it to fail without breaking the build.
  allow_failures:
    - rvm: rbx-2
  include:
    - rvm: rbx-2
      script: bundle exec rake spec
    # Run Danger only once, on 2.3.1
    - rvm: 2.3.1
      before_script: bundle exec danger

script: bundle exec rake spec rubocop
install: bundle install --jobs=1
cache: bundler
branches:
  except:
    - legacy-v2
sudo: false
