#!/usr/bin/env cap
# loads dsl, sets up stages
require 'capistrano/setup'

# provides remote execution of arbitrary commands
require 'capistrano/console'

# require bundled deployment tasks
# remove to start from scratch
require 'capistrano/deploy'

# require tasks from contrib gems
# require 'capistrano/rails'
# require 'capistrano/heroku'

# Loads any rake tasks from lib/deploy/tasks
Dir.glob('lib/deploy/tasks/*.rake').each { |r| import r }
