#!/usr/bin/env cap
# loads dsl, sets up stages
require 'capistrano/setup'

# provides remote execution of arbitrary commands
require 'capistrano/console'

# includes default deployment tasks
# remove to start completely from scratch
require 'capistrano/deploy'

# require 'capistrano/bundler'
# require 'capistrano/rails/all'
# require 'capistrano/rails/assets'
# require 'capistrano/rails/migrations'
# require 'capistrano/heroku'

# loads any rake tasks from lib/capistrano/tasks
# Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }


desc "Restart"
task :restart do
  on role(:app) do
    as deploy_user do
      # restart
    end
  end
end

after :restart, :clear_cache do
  on role(:app) do
    as deploy_user do
      # clear cache
    end
  end
end

