source "https://rubygems.org"

# keep versions up-to-date with the actual GitHub Pages setup
# https://pages.github.com/versions/

# just do `bundle update` to get the latest version.

gem "github-pages"
